image:
  repository: ghcr.io/koskev/hms-mqtt-publisher
  pullPolicy: IfNotPresent
  tag: "2024.05.06"


hms_mqtt:
  inverter_hosts:
    - "inverter.lan"
  update_interval: 30500
  #mqtt:
  #  host: "mqtt"
  #  port: 1883
  #  username: ""
  #  password: ""
  #  base_topic: "hms800wt2"
  #  serial_aliases:
  #   - serial: 1234
  #     alias: friendly_name
